### ISSUE TITLE
Resolution success highly sensitive to Unicode character choice

### ISSUE THREAD

**Issue by pkgw** [adsabs/reference_service#52]
In the process of working on the new Arxiv reference extraction pipeline ([`adsabs/arxiv-reference-extractor`][aare]), I've been using the reference resolution microservice to test out its success. It seems that the results that I'm getting out of the resolver can depend sensitively on different forms of Unicode punctuation.

[aare]: https://github.com/adsabs/arxiv-reference-extractor

Here is a file with some examples: [examples.txt](https://github.com/adsabs/reference_service/files/8154555/examples.txt). It can be processed with:

```
python test_reference_service.py -i examples.txt
```

It has a bunch of pairs of nearly-identical references. I find that for each pair, the first one resolves but the second one doesn't. In some cases, the only difference is a nearly-invisible change of an ASCII hyphen `-` to a Unicode en-dash `–`, or vice versa. In some bulk tests, I find that pure-ASCII references resolve the most successfully on average, but sometimes Unicode resolves when a plain-ASCII version doesn't.

**Comment by pkgw** [comment]
Here's another interesting example. In this file:

[2017SoPh__292__117L.txt](https://github.com/adsabs/reference_service/files/9728471/2017SoPh__292__117L.txt)

about half of the refstrings (24 out of 50) fail to resolve as-is. If I simply replace `Alfvén` with `Alfven` everywhere, nearly all of the problems are fixed — only 8 out of 50 fail.

**Comment by aaccomazzi** [comment]
This is still an issue in production at least, for example:

```Hasegawa, A., Chen, L.: 1975, Kinetic process of plasma heating due to Alfvén wave excitation. Phys. Rev. Lett. 35, 370. DOI. ADS.```

I believe there is a fix, any reason not to put it in production @golnazads?

**Comment by golnazads** [comment]
Alberto, the latest release is v2.0.17 and is running everywhere. However,
last week, I did address what Peter brought up here and it is now fixed
locally:

{
    "resolved": [
        {
            "refstring": "Hasegawa, A., Chen, L.: 1975, Kinetic process of
plasma heating due to Alfvén wave excitation. Phys. Rev. Lett. 35, 370.
DOI. ADS.",
            "score": "1.0",
            "bibcode": "1975PhRvL..35..370H"
        }
    ]
}

I have not released it yet, since I am still trying to find one other issue
that Jenny has reported. Sorry. I shall release it on Monday.
